sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-Key-Secret:
    bucket-name: java-cangqiongwaimai-wyz
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid:
    secret:
